addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    - jacoco.exec
    target_paths: 20f72323-d818-4618-88e1-af880ddb0da8
after_success:
- ' wget --content-disposition http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.7.7.201606060606/jacoco-0.7.7.201606060606.zip '
- ' unzip -o jacoco-0.7.7.201606060606.zip  '
- ' cd lib  '
- ' mv * ../  '
- ' cd ..  '
- ' chmod a+x *  '
- ' cd $PWD  '
- ' rm  ''jacoco.exec'''
- ' export JAVA_TOOL_OPTIONS=-javaagent:$PWD/jacocoagent.jar=destfile=$PWD/jacoco.exec,append=true  '
- ' travis_wait 720 mvn  test -Dmaven.test.failure.ignore=true -Djacoco.skip=true
  -Dcobertura.skip=true -Dmaven.clover.skip=true -Dmaven.javadoc.skip=true -Drat.skip=true
  -Drat.ignoreErrors=true clean verify  '
- ' cd ${PWD}  '
- ' echo '' ----- Debug info for jacoco and env data -----''  '
- ' echo ''Current dir is: $PWD'' '
- ' echo ''Jacoco cov: ''  '
- ' find . -name ''*.exec''  '
- ' echo '' ----------------------------------------------'' '
- ./df-build.sh
before_install:
- sudo /etc/init.d/mysql stop
- sudo /etc/init.d/postgresql stop
- ulimit -t unlimited -u 10000 -n 64000
- ulimit -a
- free -m
- df -h
branches: ''
cache:
  directories:
  - $HOME/.m2
  - $HOME/local
  - $HOME/.m2
git:
  depth: 150
install:
- sh dev-support/travis-install-dependencies.sh
- mvn clean install -q -ff -Dsurefire.useFile=false $HADOOP_FLAG -Pdist -DskipTests
  -Dtar
language: java
matrix:
  include:
  - before_install:
    - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g'
      $HOME/.m2/settings.xml
    env: PATH=$PATH:$HOME/local/bin HADOOP_FLAG="-Dhadoop.version=2.3.0" TEST_FLAG="test
      -pl org.apache.tajo:tajo-storage-hdfs"
    jdk: oraclejdk8
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-dev.public-swarm.devfactory.com/travisWebHookListener?build_id=20f72323-d818-4618-88e1-af880ddb0da8
script:
- mvn $HADOOP_FLAG $TEST_FLAG
- sh -c "dmesg | grep -i OOM || exit 0"
- free -m
# Modified by Insights Service at 2016-11-27 19:14:36.880525
